version: '3'
services:
  nestjs:
    build: .
    container_name: nestjs
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - .:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - .:/app
      - ./mongo-data:/data/db
networks:
  app-network:
    driver: bridge

